import type { AppLocale } from "@/lib/i18n/config";

const fr = {
  title: "Étape 1 — Comprendre votre bien et votre projet",
  intro:
    "Quelques informations suffisent pour préparer une estimation cohérente et vous orienter vers le bon accompagnement.",
  antiFriction:
    "Répondez avec les informations dont vous disposez aujourd'hui. Votre conseiller pourra compléter ou corriger les éléments avec vous si nécessaire.",
  contactDetails: "Vos coordonnées",
  firstName: "Prénom *",
  lastName: "Nom *",
  email: "Email *",
  phone: "Téléphone",
  firstNamePlaceholder: "Ex: Marie",
  lastNamePlaceholder: "Ex: Dupont",
  emailPlaceholder: "Ex: marie.dupont@email.com",
  phonePlaceholder: "Ex: 06 12 34 56 78",
  project: "Votre projet",
  projectTimeline: "Où en êtes-vous dans votre projet ?",
  timelineAlreadyListed: "Mon bien est déjà en vente",
  timelineListNow: "Je vends dès maintenant",
  timelineListWithin6Months: "Je prévois de vendre dans les 6 mois",
  timelineSelfSellFirst: "Je veux d'abord tester le marché par moi-même",
  timelineEarlyReflection: "Je réfléchis encore",
  timelinePersonalInfoOnly: "J'ai besoin d'une valeur pour une raison personnelle",
  addressAndType: "Adresse et type de bien",
  propertyType: "Type de bien",
  propertyTypeApartment: "Appartement",
  propertyTypeHouse: "Maison",
  propertyTypeVilla: "Villa",
  propertyTypeOther: "Autre",
  city: "Ville *",
  postalCode: "Code postal *",
  cityPlaceholder: "Ex: Nice",
  postalCodePlaceholder: "Ex: 06000",
  characteristics: "Caractéristiques du bien",
  surface: "Surface (m²)",
  rooms: "Pièces",
  floor: "Étage",
  buildingTotalFloors: "Nombre d'étages dans l'immeuble",
  surfacePlaceholder: "Ex: 78",
  roomsPlaceholder: "Ex: 3",
  floorPlaceholder: "Ex: 4",
  buildingTotalFloorsPlaceholder: "Ex: 6",
  terrace: "Terrasse *",
  terraceArea: "Taille de la terrasse (m²)",
  terraceAreaPlaceholder: "Ex: 12",
  balcony: "Balcon *",
  balconyArea: "Taille du balcon (m²)",
  balconyAreaPlaceholder: "Ex: 6",
  select: "Sélectionner",
  yes: "Oui",
  no: "Non",
  exposure: "Exposition du séjour",
  exposureNorth: "Nord",
  exposureNorthEast: "Nord Est",
  exposureEast: "Est",
  exposureSouthEast: "Sud Est",
  exposureSouth: "Sud",
  exposureSouthWest: "Sud Ouest",
  exposureWest: "Ouest",
  exposureNorthWest: "Nord Ouest",
  elevator: "Ascenseur *",
  apartmentCondition: "État de l'appartement *",
  apartmentConditionToRenovate: "À rénover",
  apartmentConditionRenovated20: "Rénové il y a 20 ans",
  apartmentConditionRenovated10: "Rénové il y a 10 ans",
  apartmentConditionRenovated5: "Rénové il y a moins de 5 ans",
  apartmentConditionNew: "Neuf",
  buildingAge: "Âge de l'immeuble (optionnel)",
  notSpecified: "Non renseigné",
  buildingAgeOld: "Ancien (jusqu'à 1950)",
  buildingAgeRecent: "Récent (1950-1970)",
  buildingAgeModern: "Moderne (1980 - Aujourd'hui)",
  seaView: "Vue mer",
  seaViewPanoramic: "Vue mer panoramique",
  seaViewClassic: "Vue mer classique",
  seaViewLateral: "Vue mer latérale",
  topFloor: "Dernier étage",
  usefulInfo: "Informations utiles (optionnel)",
  usefulInfoPlaceholder: "Ex : travaux récents, contraintes de calendrier, contexte particulier...",
  send: "Sécuriser mon estimation",
  sending: "Envoi...",
};

export type SellerProjectFormCopy = typeof fr;

export const SELLER_PROJECT_FORM_COPY: Record<AppLocale, SellerProjectFormCopy> = {
  fr,
  en: {
    title: "Step 1 — Understanding your property and project",
    intro:
      "A few details are enough to prepare a coherent valuation and guide you towards the right level of support.",
    antiFriction:
      "Answer with the information you have today. Your advisor can complete or adjust the details with you if needed.",
    contactDetails: "Your contact details",
    firstName: "First name *",
    lastName: "Last name *",
    email: "Email *",
    phone: "Phone",
    firstNamePlaceholder: "Ex: Marie",
    lastNamePlaceholder: "Ex: Dupont",
    emailPlaceholder: "Ex: marie.dupont@email.com",
    phonePlaceholder: "Ex: +33 6 12 34 56 78",
    project: "Your project",
    projectTimeline: "Where are you in your project?",
    timelineAlreadyListed: "My property is already for sale",
    timelineListNow: "I am selling right now",
    timelineListWithin6Months: "I plan to sell within the next 6 months",
    timelineSelfSellFirst: "I want to test the market on my own first",
    timelineEarlyReflection: "I am still considering my options",
    timelinePersonalInfoOnly: "I need a value for a personal reason",
    addressAndType: "Address and property type",
    propertyType: "Property type",
    propertyTypeApartment: "Apartment",
    propertyTypeHouse: "House",
    propertyTypeVilla: "Villa",
    propertyTypeOther: "Other",
    city: "City *",
    postalCode: "Postal code *",
    cityPlaceholder: "Ex: Nice",
    postalCodePlaceholder: "Ex: 06000",
    characteristics: "Property features",
    surface: "Surface area (sqm)",
    rooms: "Rooms",
    floor: "Floor",
    buildingTotalFloors: "Number of floors in the building",
    surfacePlaceholder: "Ex: 78",
    roomsPlaceholder: "Ex: 3",
    floorPlaceholder: "Ex: 4",
    buildingTotalFloorsPlaceholder: "Ex: 6",
    terrace: "Terrace *",
    terraceArea: "Terrace size (sqm)",
    terraceAreaPlaceholder: "Ex: 12",
    balcony: "Balcony *",
    balconyArea: "Balcony size (sqm)",
    balconyAreaPlaceholder: "Ex: 6",
    select: "Select",
    yes: "Yes",
    no: "No",
    exposure: "Living room exposure",
    exposureNorth: "North",
    exposureNorthEast: "North-East",
    exposureEast: "East",
    exposureSouthEast: "South-East",
    exposureSouth: "South",
    exposureSouthWest: "South-West",
    exposureWest: "West",
    exposureNorthWest: "North-West",
    elevator: "Elevator *",
    apartmentCondition: "Apartment condition *",
    apartmentConditionToRenovate: "To renovate",
    apartmentConditionRenovated20: "Renovated 20 years ago",
    apartmentConditionRenovated10: "Renovated 10 years ago",
    apartmentConditionRenovated5: "Renovated less than 5 years ago",
    apartmentConditionNew: "New",
    buildingAge: "Building age (optional)",
    notSpecified: "Not provided",
    buildingAgeOld: "Historic (up to 1950)",
    buildingAgeRecent: "Recent (1950-1970)",
    buildingAgeModern: "Modern (1980 - today)",
    seaView: "Sea view",
    seaViewPanoramic: "Panoramic sea view",
    seaViewClassic: "Sea view",
    seaViewLateral: "Partial sea view",
    topFloor: "Top floor",
    usefulInfo: "Useful details (optional)",
    usefulInfoPlaceholder: "Ex: recent works, timing constraints, special context...",
    send: "Secure my valuation",
    sending: "Sending...",
  },
  es: {
    title: "Paso 1 — Entender su inmueble y su proyecto",
    intro:
      "Unos pocos datos bastan para preparar una valoración coherente y orientarle hacia el acompañamiento adecuado.",
    antiFriction:
      "Responda con la información de la que dispone hoy. Su asesor podrá completar o ajustar los elementos con usted si es necesario.",
    contactDetails: "Sus datos de contacto",
    firstName: "Nombre *",
    lastName: "Apellidos *",
    email: "Email *",
    phone: "Teléfono",
    firstNamePlaceholder: "Ej: María",
    lastNamePlaceholder: "Ej: Dupont",
    emailPlaceholder: "Ej: maria.dupont@email.com",
    phonePlaceholder: "Ej: +33 6 12 34 56 78",
    project: "Su proyecto",
    projectTimeline: "¿En qué punto se encuentra su proyecto?",
    timelineAlreadyListed: "Mi inmueble ya está en venta",
    timelineListNow: "Vendo ahora mismo",
    timelineListWithin6Months: "Tengo previsto vender en los próximos 6 meses",
    timelineSelfSellFirst: "Primero quiero probar el mercado por mi cuenta",
    timelineEarlyReflection: "Aún lo estoy pensando",
    timelinePersonalInfoOnly: "Necesito un valor por un motivo personal",
    addressAndType: "Dirección y tipo de inmueble",
    propertyType: "Tipo de inmueble",
    propertyTypeApartment: "Apartamento",
    propertyTypeHouse: "Casa",
    propertyTypeVilla: "Villa",
    propertyTypeOther: "Otro",
    city: "Ciudad *",
    postalCode: "Código postal *",
    cityPlaceholder: "Ej: Niza",
    postalCodePlaceholder: "Ej: 06000",
    characteristics: "Características del inmueble",
    surface: "Superficie (m²)",
    rooms: "Habitaciones",
    floor: "Planta",
    buildingTotalFloors: "Número de plantas del edificio",
    surfacePlaceholder: "Ej: 78",
    roomsPlaceholder: "Ej: 3",
    floorPlaceholder: "Ej: 4",
    buildingTotalFloorsPlaceholder: "Ej: 6",
    terrace: "Terraza *",
    terraceArea: "Tamaño de la terraza (m²)",
    terraceAreaPlaceholder: "Ej: 12",
    balcony: "Balcón *",
    balconyArea: "Tamaño del balcón (m²)",
    balconyAreaPlaceholder: "Ej: 6",
    select: "Seleccionar",
    yes: "Sí",
    no: "No",
    exposure: "Orientación del salón",
    exposureNorth: "Norte",
    exposureNorthEast: "Noreste",
    exposureEast: "Este",
    exposureSouthEast: "Sureste",
    exposureSouth: "Sur",
    exposureSouthWest: "Suroeste",
    exposureWest: "Oeste",
    exposureNorthWest: "Noroeste",
    elevator: "Ascensor *",
    apartmentCondition: "Estado del apartamento *",
    apartmentConditionToRenovate: "Para reformar",
    apartmentConditionRenovated20: "Reformado hace 20 años",
    apartmentConditionRenovated10: "Reformado hace 10 años",
    apartmentConditionRenovated5: "Reformado hace menos de 5 años",
    apartmentConditionNew: "Nuevo",
    buildingAge: "Antigüedad del edificio (opcional)",
    notSpecified: "No indicado",
    buildingAgeOld: "Antiguo (hasta 1950)",
    buildingAgeRecent: "Reciente (1950-1970)",
    buildingAgeModern: "Moderno (1980 - hoy)",
    seaView: "Vista al mar",
    seaViewPanoramic: "Vista panorámica al mar",
    seaViewClassic: "Vista al mar",
    seaViewLateral: "Vista lateral al mar",
    topFloor: "Última planta",
    usefulInfo: "Información útil (opcional)",
    usefulInfoPlaceholder: "Ej: obras recientes, restricciones de calendario, contexto particular...",
    send: "Asegurar mi valoración",
    sending: "Envío...",
  },
  ru: {
    title: "Шаг 1 — Понять ваш объект и ваш проект",
    intro:
      "Нескольких данных достаточно, чтобы подготовить связную оценку и направить вас к нужному уровню сопровождения.",
    antiFriction:
      "Укажите ту информацию, которая у вас есть сегодня. Ваш консультант сможет дополнить или уточнить детали вместе с вами при необходимости.",
    contactDetails: "Ваши контактные данные",
    firstName: "Имя *",
    lastName: "Фамилия *",
    email: "Email *",
    phone: "Телефон",
    firstNamePlaceholder: "Например: Мария",
    lastNamePlaceholder: "Например: Иванова",
    emailPlaceholder: "Например: maria.dupont@email.com",
    phonePlaceholder: "Например: +33 6 12 34 56 78",
    project: "Ваш проект",
    projectTimeline: "На каком этапе ваш проект?",
    timelineAlreadyListed: "Мой объект уже выставлен на продажу",
    timelineListNow: "Я продаю прямо сейчас",
    timelineListWithin6Months: "Планирую продать в течение 6 месяцев",
    timelineSelfSellFirst: "Сначала хочу попробовать рынок самостоятельно",
    timelineEarlyReflection: "Пока ещё обдумываю",
    timelinePersonalInfoOnly: "Мне нужна стоимость по личной причине",
    addressAndType: "Адрес и тип объекта",
    propertyType: "Тип объекта",
    propertyTypeApartment: "Квартира",
    propertyTypeHouse: "Дом",
    propertyTypeVilla: "Вилла",
    propertyTypeOther: "Другое",
    city: "Город *",
    postalCode: "Почтовый индекс *",
    cityPlaceholder: "Например: Ницца",
    postalCodePlaceholder: "Например: 06000",
    characteristics: "Характеристики объекта",
    surface: "Площадь (м²)",
    rooms: "Комнаты",
    floor: "Этаж",
    buildingTotalFloors: "Количество этажей в здании",
    surfacePlaceholder: "Например: 78",
    roomsPlaceholder: "Например: 3",
    floorPlaceholder: "Например: 4",
    buildingTotalFloorsPlaceholder: "Например: 6",
    terrace: "Терраса *",
    terraceArea: "Площадь террасы (м²)",
    terraceAreaPlaceholder: "Например: 12",
    balcony: "Балкон *",
    balconyArea: "Площадь балкона (м²)",
    balconyAreaPlaceholder: "Например: 6",
    select: "Выбрать",
    yes: "Да",
    no: "Нет",
    exposure: "Ориентация гостиной",
    exposureNorth: "Север",
    exposureNorthEast: "Северо-восток",
    exposureEast: "Восток",
    exposureSouthEast: "Юго-восток",
    exposureSouth: "Юг",
    exposureSouthWest: "Юго-запад",
    exposureWest: "Запад",
    exposureNorthWest: "Северо-запад",
    elevator: "Лифт *",
    apartmentCondition: "Состояние квартиры *",
    apartmentConditionToRenovate: "Требует ремонта",
    apartmentConditionRenovated20: "Отремонтировано 20 лет назад",
    apartmentConditionRenovated10: "Отремонтировано 10 лет назад",
    apartmentConditionRenovated5: "Отремонтировано менее 5 лет назад",
    apartmentConditionNew: "Новое",
    buildingAge: "Возраст здания (необязательно)",
    notSpecified: "Не указано",
    buildingAgeOld: "Старое здание (до 1950 года)",
    buildingAgeRecent: "Недавнее (1950-1970)",
    buildingAgeModern: "Современное (1980 - сегодня)",
    seaView: "Вид на море",
    seaViewPanoramic: "Панорамный вид на море",
    seaViewClassic: "Вид на море",
    seaViewLateral: "Боковой вид на море",
    topFloor: "Последний этаж",
    usefulInfo: "Полезная информация (необязательно)",
    usefulInfoPlaceholder: "Например: недавние работы, ограничения по срокам, особый контекст...",
    send: "Защитить мою оценку",
    sending: "Отправка...",
  },
};
