import "server-only";
import { unstable_cache } from "next/cache";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { callOpenAiChat } from "@/lib/ai/openai";
import { logConversationTurn } from "@/lib/ai/conversation-logger";
import {
  SILLAGE_AGENCY_KNOWLEDGE,
  SILLAGE_AGENCY_KNOWLEDGE_VERSION,
} from "@/lib/ai/knowledge/sillage-agency-knowledge";
import { getDashboardSnapshot } from "./dashboard-aggregator.service";

// IA syntheses for the admin pilot dashboard.
//
// Four short, opinionated paragraphs (4–6 sentences each) that summarize
// the most actionable signals across the agency: market trends, risk
// signals, matching opportunities, and "voice of the market" (what
// visitors are actually asking the homepage IA).
//
// Each synthesis:
//   - is generated by gpt-4o-mini at temperature 0.3
//   - is persisted as an ai_conversations row (entity_type='admin',
//     channel='admin_console', model='gpt-4o-mini') so we can audit /
//     replay them
//   - is cached for 1h via unstable_cache, keyed by section id

export type SynthesisSection =
  | "market_trends"
  | "risk_signals"
  | "matching_opportunities"
  | "market_voice";

export type SynthesisResult = {
  section: SynthesisSection;
  generatedAt: string;
  body: string;
  model: string;
  conversationId: string | null;
  tokensTotal: number;
  costMicros: number;
  warning?: string;
};

const SYSTEM_PROMPT = `Tu es l'analyste de pilotage de Sillage Immo (agence immobilière haut de gamme à Nice).
Tu rédiges des synthèses courtes, opérationnelles et factuelles pour le manager/administrateur de l'agence à partir des indicateurs internes.
Tu réponds toujours en français, dans un ton professionnel et neutre.
Format de réponse strict : 4 à 6 phrases maximum, pas de liste à puces, pas de Markdown.
Garde-fous Sillage Immo :
- Ne donne JAMAIS de prix ou de valorisation chiffrée précise (toujours fourchette + redirige vers conseiller).
- Ne donne aucun conseil juridique ferme.
- Ne nomme aucun client par son nom ; ne mentionne aucun email ou téléphone.
- Si les données sont insuffisantes ou incohérentes, dis-le explicitement et propose une action concrète.`;

const SECTION_PROMPT: Record<SynthesisSection, { title: string; question: string }> = {
  market_trends: {
    title: "Tendances marché",
    question:
      "Analyse les tendances marché des 30 derniers jours (volume de leads vendeurs vs acquéreurs, dynamique des zones top, évolution vs période précédente). Identifie 1 à 2 inflexions notables et propose 1 action concrète.",
  },
  risk_signals: {
    title: "Risques détectés",
    question:
      "Identifie les risques opérationnels visibles dans les indicateurs (baisses brutales, stagnation des mandats, déséquilibre de la performance entre conseillers, conversion en chute). Reste factuel et propose 1 mesure corrective.",
  },
  matching_opportunities: {
    title: "Opportunités matching",
    question:
      "À partir du volume de leads acquéreurs récents et de la dynamique des mandats signés, identifie les opportunités de matching à activer en priorité cette semaine (zones, types de biens). Conclus par 1 action concrète.",
  },
  market_voice: {
    title: "Voix du marché",
    question:
      "Analyse les sujets / mots-clés qui ressortent des conversations IA client des 7 derniers jours. Que demandent vraiment les visiteurs ? Qu'est-ce qui mérite d'être mis en avant ou retravaillé dans nos parcours digitaux ?",
  },
};

const buildContextPayload = async (section: SynthesisSection) => {
  const snapshot = await getDashboardSnapshot();
  return {
    agencyKnowledgeVersion: SILLAGE_AGENCY_KNOWLEDGE_VERSION,
    agencyKnowledge: SILLAGE_AGENCY_KNOWLEDGE,
    sectionTitle: SECTION_PROMPT[section].title,
    question: SECTION_PROMPT[section].question,
    indicators: {
      periodDays: snapshot.periodDays,
      kpis: snapshot.kpis,
      funnel: snapshot.funnel,
      topZones: snapshot.topZones,
      // Advisor perf is sensitive — we still include it in the context
      // because the synthesis is only visible to manager+admin (RBAC
      // enforced in the page route handler).
      advisors:
        section === "risk_signals" || section === "market_trends"
          ? snapshot.advisors
          : [],
      conversations: snapshot.conversations,
    },
  };
};

const computeSynthesis = async (
  section: SynthesisSection
): Promise<SynthesisResult> => {
  const payload = await buildContextPayload(section);
  const generatedAt = new Date().toISOString();

  try {
    const chatResult = await callOpenAiChat({
      model: "gpt-4o-mini",
      temperature: 0.3,
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: JSON.stringify(payload) },
      ],
      toolName: `admin_dashboard.synthesis.${section}`,
      toolVersion: "1.0.0",
    });

    const body = chatResult.content.trim();

    let conversationId: string | null = null;
    try {
      const logResult = await logConversationTurn({
        entityType: "admin",
        channel: "admin_console",
        model: chatResult.model,
        locale: "fr",
        userMessage: `[admin_dashboard.synthesis.${section}] ${SECTION_PROMPT[section].question}`,
        assistantMessage: body,
        usage: {
          tokensIn: chatResult.usage.promptTokens,
          tokensOut: chatResult.usage.completionTokens,
          costMicros: chatResult.costMicros,
        },
        finishReason: chatResult.finishReason,
        toolName: `admin_dashboard.synthesis.${section}`,
        toolVersion: "1.0.0",
        metadata: {
          synthesis_section: section,
          knowledge_version: SILLAGE_AGENCY_KNOWLEDGE_VERSION,
          generated_at: generatedAt,
        },
        closeAfter: true,
      });
      conversationId = logResult.conversationId;
    } catch {
      // non-blocking
    }

    return {
      section,
      generatedAt,
      body,
      model: chatResult.model,
      conversationId,
      tokensTotal: chatResult.usage.totalTokens,
      costMicros: chatResult.costMicros,
    };
  } catch (error) {
    const message =
      error instanceof Error ? error.message : "OpenAI synthesis failed";
    return {
      section,
      generatedAt,
      body:
        "Synthèse IA temporairement indisponible. Vérifiez OPENAI_API_KEY et réessayez dans quelques minutes.",
      model: "gpt-4o-mini",
      conversationId: null,
      tokensTotal: 0,
      costMicros: 0,
      warning: message,
    };
  }
};

const cachedSynthesis = (section: SynthesisSection) =>
  unstable_cache(
    async () => computeSynthesis(section),
    [`admin-dashboard-synthesis-v1-${section}`],
    {
      revalidate: 3600,
      tags: ["admin-dashboard-pilot", `admin-dashboard-synthesis-${section}`],
    }
  );

export const getMarketTrendsSynthesis = cachedSynthesis("market_trends");
export const getRiskSignalsSynthesis = cachedSynthesis("risk_signals");
export const getMatchingOpportunitiesSynthesis = cachedSynthesis(
  "matching_opportunities"
);
export const getMarketVoiceSynthesis = cachedSynthesis("market_voice");

export const getAllSyntheses = async (): Promise<SynthesisResult[]> => {
  const [trends, risks, opportunities, voice] = await Promise.all([
    getMarketTrendsSynthesis().catch(
      () => null as SynthesisResult | null
    ),
    getRiskSignalsSynthesis().catch(() => null as SynthesisResult | null),
    getMatchingOpportunitiesSynthesis().catch(
      () => null as SynthesisResult | null
    ),
    getMarketVoiceSynthesis().catch(() => null as SynthesisResult | null),
  ]);
  return [trends, risks, opportunities, voice].filter(
    (s): s is SynthesisResult => s !== null
  );
};

// supabaseAdmin is imported eagerly so any RLS regression on
// ai_conversations / ai_messages would surface at boot rather than at
// first dashboard hit. (No-op at runtime.)
void supabaseAdmin;
